accounts/urls.py
from django.urls import path
from .views import HomeView

app_name = 'accounts'
urlpatterns = [
   path('home/', HomeView.as_view(), name='home'),
]

party_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # mediaを使うために追加
from . import settings  # mediaを使うために追加

urlpatterns = [
   path('admin/', admin.site.urls),
   path('accounts/', include('allauth.urls')),  
   path('accounts/', include('accounts.urls')),  
   path('post/', include('post.urls')),
]

if settings.DEBUG:
   urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)  
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   

post/urls.py
from django.urls import path
from .views import (
   profile,PostCreateView,PostListView,PostUpdateView,PostDeleteView,MyPostsView,ProfileEditView , UserListView
)
app_name = 'post'
urlpatterns = [
   path('create/', PostCreateView.as_view(), name='create'),
   path('postlist/',PostListView.as_view(),name='postlist'),
   path('update/<int:pk>',PostUpdateView.as_view(),name='update'),
   path('delete/<int:pk>',PostDeleteView.as_view(), name='delete'),
   path('mypost/',MyPostsView.as_view(), name='mypost'),
   path('edit_profile/', ProfileEditView.as_view(), name='edit_profile'), 
   path('userlist/',  UserListView.as_view(), name='userlist'),
   path('profile/' ,profile, name='profile'),
]

post/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='オーナー', on_delete=models.CASCADE)
    content = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        db_table = 'posts'
        ordering = ["-created_at"]

post/forms.py
from django import forms
from .models import Post
from accounts.models import CustomUser
from django.contrib.admin.widgets import AdminDateWidget




class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'content',
        )
        widgets = {
            'content': forms.Textarea(
                attrs={'rows': 5, 'cols': 30,
                        'placeholder': 'ここに入力してください'}
            ),
        
        }

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'content',
        )
        widgets = {
            'content':forms.Textarea(
                attrs={'rows':5,'cols':30}
            ),
        }

class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):#*argsはtuple型**kwargsはdict型
        super(ProfileForm, self).__init__(*args, **kwargs)

        for field in self.fields.values():  # bootstrapで使用するform-controlクラス
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = CustomUser
        fields = ('nickname','email','comment','birthday','avatar')
        help_texts = {
            'nickname': "ユーザーネーム",
            'email': None,
            'comment':"自己紹介",
            'birthday':"生年月日",
            
            
        }        

post/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic import ListView,DetailView,View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post
from .forms import PostCreateForm,PostUpdateForm
from django.contrib import messages
from django.urls import reverse_lazy
from accounts.models import CustomUser
from .forms import ProfileForm 


class PostCreateView(LoginRequiredMixin, CreateView): #モデルオブジェクト作成クラス
    template_name = 'post/create.html'
    form_class = PostCreateForm
    success_url = reverse_lazy('post:mypost')
    
    def form_valid(self, form):
        # request.userが一つのセットでAuthenticationMiddlewareでセットされている。
        form.instance.owner_id = self.request.user.id
        messages.success(self.request, '投稿が完了しました')
        return super(PostCreateView, self).form_valid(form)
        
    def form_invalid(self, form):
        messages.warning(self.request, '投稿が失敗しました')
        return redirect('post:create')

class PostListView(LoginRequiredMixin,ListView):# #モデルオブジェクトの一覧を表示する
    template_name ='post/postlist.html'
    model = Post
    # paginate_by =5 様子見 テンプレート側を消すのをわすれないで

    def get_queryset(self):
        return Post.objects.all()


class PostUpdateView(LoginRequiredMixin, UpdateView): 
    model = Post
    form_class = PostUpdateForm
    template_name = 'post/update.html'
    success_url = reverse_lazy('post:mypost')


    def form_valid(self, form):
        messages.success(self.request, '更新が完了しました')
        return super(PostUpdateView, self).form_valid(form)
        
    def get_success_url(self):
        return reverse_lazy('post:update', kwargs={'pk': self.object.id})  
        
    def form_invalid(self, form):
        messages.warning(self.request, '更新が失敗しました')
        return reverse_lazy('post:update', kwargs={'pk': self.object.id})
#見直し

class PostDeleteView(LoginRequiredMixin,DeleteView):# #モデルオブジェクトの削除を表示する
    model = Post
    template_name = 'post/delete.html'
    success_url =reverse_lazy('post:mypost')
    success_message ="投稿は削除しました。"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(PostDeleteView, self).delete(request, *args, **kwargs)


class MyPostsView(LoginRequiredMixin, ListView): # 自分の投稿を見れるようにする
    
    template_name = 'post/mypost.html'
    model = Post

    # Postsテーブルのowner_idが自分自身の全データを取得するメソッド定義
    def get_queryset(self):  # 自分の投稿オブジェクトを返す。
        return Post.objects.filter(owner_id=self.request.user)
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Postsテーブルの自分の投稿数をmy_posts_countへ格納
        context['my_posts_count'] = Post.objects.filter(owner_id=self.request.user).count()
        context['data']=CustomUser.objects.filter(email=self.request.user)
        return context







class ProfileEditView(LoginRequiredMixin, UpdateView): # ユーザー情報の編集
    template_name = 'post/edit_profile.html'
    model = CustomUser
    form_class = ProfileForm
    success_url = '/post/mypost/'
    
    def get_object(self):
        return self.request.user







class UserListView(LoginRequiredMixin, ListView): 
    template_name = 'post/userlist.html'
    model =CustomUser
    
    def get_queryset(self):
        
        return CustomUser.objects.all()        




def profile(request):
    data = CustomUser.objects.filter(email=request.user)
    params = {
        'title':'自己紹介',
        'data': data,
    }
    return render(request, 'post/profile.html',params)

post/templates/post/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>party_app</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% load bootstrap4 %}
</head>
<body>
<header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url  'accounts:home' %}"> home</a> 
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
            </ul>
            <ul class="navbar-nav navbar-right">{% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>

                <li class="nav-item">
                    <a class="nav-link"href="{% url 'post:create' %}">new </a>   

                <li class="nav-item">
                    <a class="nav-link"href="{% url 'post:postlist' %}">all </a>     

                </li>{% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">Sign in</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>
{% block content %}
    
{% endblock content %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS,Fontawasome -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>

{% block footer %}
{% endblock footer %}
</body>
</html>

post/templates/post/create.html
{% extends 'post/base.html' %}

{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 offset-sm-3">
                    {#  views.pyからmessagesが渡された場合にのみメッセージを表示させる。#}
                    {% if messages %}
                        {% for message in messages %}
                            {#   message/tagsはSettings.pyで設定している#}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                {{ message }}
                            </li>
                        {% endfor %}
                    {% endif %}
                    <div class="card">
                        <div class="card-header">
                            <h4><b>新規投稿</b></h4>
                        </div>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                <button type="submit" class="btn btn-outline-primary btn-block">
                                    投稿する
                                </button>
                            </form>
                        </div>
                        <a class="nav-link" href="{% url 'post:mypost' %}">戻る</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

post/templates/post/delete.html
{% extends 'post/base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 offset-sm-3">
    <a class="nav-link" href="{% url 'post:mypost' %}">戻る</a>
{% endblock %}                

post/templates/post/edit_profile.html
{% extends 'post/base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 offset-sm-3">
                    <div class="card">
                        <div class="card-header">
                            <h4><b>プロフィール更新</b></h4>
                        </div>
                        <div class="card-body">
                            {# 画像ファイルをアップロードするためenctype="multipart/form-data"を指定#}
                            <form action="{% url  'post:edit_profile' %}" method="post"
                                    enctype="multipart/form-data">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                <button class='btn btn-outline-success btn-block' type="submit">更新</button>

                            </form>
                            <a class="nav-link" href="{% url 'post:mypost' %}">戻る</a>
                        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        </form>
    </nav>
{% endblock %}

post/templates/post/mypost.html
{% extends 'post/base.html' %}
{% load static %}
{% block content %}

    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <aside class="col-sm-3">
                    <div class="card">
                        <div class="card-header">
                            {% for item in  data  %}
                            <h2><strong><a>{{ item.nickname }}</a></strong></h2>
                    
                            {% endfor %}
                        </div>
                        <div class="card-body">
                            {# ユーザーがプロフィール画像を持っている場合#}
                            {% if user.avatar %}
                                <img class="rounded img-fluid mx-auto d-block"
                                    src="{{ user.avatar.url }}" id="avatar-image" alt="avatar_image">
                                {# ユーザーがプロフィール画像を持っている場合はデフォルト画像を表示#}
                            {% else %}
                                <img class="rounded img-fluid mx-auto d-block"
                                    src="{% static 'images/avator_default.png' %}" id="avatar-image" alt="avatar_image">
                            {% endif %}
                        </div>
                        <a class="btn btn-outline-secondary btn-sm"
                            href="{% url 'post:edit_profile' %}" role="button">プロフィール更新</a>
                    </div>
                </aside>
                <div class="box" align="right">
                    <div class="col-30 clearfix">
                        <div class="alert alert-success" role="alert">
                            <h4 class="alert-heading">
                                <div class="button010">
                                    <a href="#">自己紹介</a>
                                </div> 
                    
                        </div>
                        <div class="card" style="width: 40rem;">
                            <div class="card-body">
                                <div class="dashed-note">
                                    
                                    <h3 class="card-title"></h3>
                                    {% for item in data %}
                        　　　　　　 <td>{{item.comment}}</td>
                        　　　　　　　{% endfor %}
                                    <h3 class="card-subtitle mb-5 text-muted"></h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
            
                <div class="col-sm-8">
                    <ul class="nav nav-tabs nav-justif ied mb-3">
                        <li class="nav-item"><a href="{% url 'post:mypost' %}" class="nav-link active">MyPosts一覧
                            {#  object_listのlengthを取得することで投稿数をカウントできる。#}
                            <span class="badge badge-secondary">{{ my_posts_count }}</span></a></li>
                        <li class="nav-item"><a href="#" class="nav-link">相性のいい人
                            {#  相性いい人の数を表示#}
                    
                    </ul>
                    <!-- テーブル表の定義 -->
                    <div class="table table-responsive">
                        <table id='post_list'
                                class="table table-striped table-bordered table-hover">
                            　<!-- 表の列の定義-->
                            <thead>
                            <tr>
                                <th class="text-center" style="width: 80%">投稿内容</th>
                                <th class="text-center" style="width: 20%">更新／削除</th>
                            </tr>
                            </thead>
                            　<!-- ここまでが表の列の定義-->
                            　<!-- 表のデータ部分の表示-->
                            <tbody>
                            {% for item in object_list %}
                                <tr class="text">
                                    <td class="text"><h6>@{{ item.created_at }}</h6>{{ item.content }}</td>
                                    <td class="text-center align-middle">
                                        {#  pkを指定する際は、urlタグはやや特殊な書き方となる↓以下参照#}
                                        <a class="btn btn-outline-success btn-sm"
                                            href="{% url 'post:update' item.pk %}"
                                            role="button">更新</a>
                                        <a class="btn btn-outline-danger btn-sm"
                                            href="{% url 'post:delete' item.pk %}"
                                            role="button">削除</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            　<!-- ここまでが表のデータ部分の表示-->
                        </table>
                        <!-- ここまでがテーブル表の定義 -->
                    </div>
                </div>
            </div>
{% endblock %}

post/templates/post/postlist.html
{% extends 'post/base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <!--ページタイトル-->
            <div class="card mb-3">
                <div class="card-header">
                    <h4><b>投稿一覧</b></h4>
                </div>
                <div class="card-body">
                    <!-- テーブル表の定義 -->
                    <div class="table table-responsive">
                        <table id='post_list' class="table table-striped table-bordered table-hover">
                            　 <!-- 表の列の定義-->
                            <thead>
                            <tr>
                                <th class="text-center">投稿内容</th>
                                <th class="text-center">name</th>
                            </tr>
                            </thead>
                            　<!-- ここまでが表の列の定義-->
                            　<!-- 表のデータ部分の表示-->
                            <tbody>
                            {# デフォルトはobject_listとなるが、view.pyでcontextとして指定#}
                            {% for item in object_list %}
                                <tr class="text">
                                    <td class="text" style="width: 80%">
                                        <h6>{{ item.owner }}@{{ item.created_at}}</h6>{{ item.content }}</td>
                                    <td class="text-center align-middle" style="width: 20%">
                                        ・・・準備中・・・
                                    </td>                                  
                                </tr>
                            {% endfor %}
                            </tbody>
                            　<!-- ここまでが表のデータ部分の表示-->
                        </table>
                        <!-- ここまでがテーブル表の定義 -->
                    </div>
                    <a class="nav-link" href="{% url 'post:mypost' %}">戻る</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

post/templates/post/update.html
{% extends 'post/base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 offset-sm-3">
                    {#  views.pyからmessagesが渡された場合にのみメッセージを表示させる。#}
                    {% if messages %}
                        {% for message in messages %}
                            {#   message/tagsはSettings.pyで設定している#}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                {{ message }}
                            </li>
                        {% endfor %}
                    {% endif %}
                    <div class="card">
                        <div class="card-header">
                            <h4><b>投稿編集</b></h4>
                        </div>
                        {% if object.owner_id == user.id %}
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                <button type="submit" class="btn btn-outline-primary btn-block">
                                    更新する
                                </button>
                            </form>
                        {% else %}
                        <p class='font-weight-bold text-danger text-center'>
                            {{ user.get_username}}さんの投稿ではありません。
                        </p>  
                        {% endif %}
                    </div>
                    <a class="nav-link" href="{% url 'post:mypost' %}">戻る</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

post/templates/post/userlist.html
{% extends 'post/base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <!--ページタイトル-->
            <div class="card mb-3">
                <div class="card-header">
                    <h4><b> ユーザー 一覧</b></h4>
                </div>
                <div class="card-body">
                    <!-- テーブル表の定義 -->
                    <div class="table table-responsive">
                        <table id='user_list' width="100%" class="table table-striped table-bordered table-hover">
                            <!-- 表の列の定義-->
                            <thead>
                            <tr>
                            <th class="text-center">ユーザー</th>
                                <th class="text-center">画像</th>
                            </tr>
                            </thead>
                            <!-- ここまでが表の列の定義-->
                            <!-- 表のデータ部分の表示-->
                            <tbody>
                            {# デフォルトはobject_listとなるが、view.pyでcontextとして指定することも出来る#}
                            {% for item in object_list %}
                                <tr class="odd gradeX text-center">
                                    <td class="text-center" style="width: 50%">{{ item.username }}</td>
                                    <td class="text-center" style="width: 50%">
                                {# ユーザーがプロフィール画像を持っている場合#}
                                {% if item.avatar %}
                                    <img class="rounded img-fluid mx-auto d-block" src="{{ item.avatar.url }}"
                                    id="avatar-thumbnail" alt="avatar_thumbnail">
                                {# ユーザーがプロフィール画像を持ってない場合は”avatar_thumbnailを表示 #}
                                {% else %}
                                    <img class="rounded img-fluid mx-auto d-block" alt="avatar_thumbnail">
                                {% endif %}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            　<!-- ここまでが表のデータ部分の表示-->
                        </table>
                        <!-- ここまでがテーブル表の定義 -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}